# Generated by Django 3.2.15 on 2022-10-11 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0007_book_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
